site_name: Documentation
site_url: https://www.codbex.com/

nav:
  - Home: 
    - 'index.md'
    - Getting Started: 'getting-started.md'
    - Products: '../products/'
    # - Solutions: '../solutions/'
    - Services: '../services/'
    - Pricing: '../pricing/'
    - Announcements: '/categories/marketing/'
    - Tutorials: '/categories/technology/'
    - Configurations: 
      - 'configurations/index.md'
      - Basic Authentication: 'configurations/basic-auth.md'
  - Platform:
    - 'platform/index.md'
    - Languages: 'platform/languages/index.md'
    - Engines: 
      - 'platform/engines/index.md'
      - JavaScript: 'platform/engines/javascript.md'
      - TypeScript: 'platform/engines/typescript.md'
      - Python: 'platform/engines/python.md'
      - Command: 'platform/engines/command.md'
      - Jobs: 'platform/engines/jobs.md'
      - Listeners: 'platform/engines/listeners.md'
      - Web: 'platform/engines/web.md'
      - Wiki: 'platform/engines/wiki.md'
      - WebSockets: 'platform/engines/websockets.md'
      - Security: 'platform/engines/security.md'
      - OpenAPI: 'platform/engines/openapi.md'
      - OData: 'platform/engines/odata.md'
      - Templates: 'platform/engines/templates.md'
      - CMS: 'platform/engines/cms.md'
      - BPM: 'platform/engines/bpm.md'
      - Integrations: 'platform/engines/integrations.md'
      - FTP: 'platform/engines/ftp.md'
      - SFTP: 'platform/engines/sftp.md'
    - Artefacts:
      - 'platform/artefacts/index.md'
      - access: platform/artefacts/access.md
      - bpmn: platform/artefacts/bpmn.md
      - camel: platform/artefacts/camel.md
      - command: platform/artefacts/command.md
      - confluence: platform/artefacts/confluence.md
      - csv: platform/artefacts/csv.md
      - csvim: platform/artefacts/csvim.md
      - datasource: platform/artefacts/datasource.md
      - dsm: platform/artefacts/dsm.md
      - edm:  platform/artefacts/edm.md
      - entity: platform/artefacts/entity.md
      - exposes: platform/artefacts/exposes.md
      - extension: platform/artefacts/extension.md
      - extensionpoint: platform/artefacts/extensionpoint.md
      - form: platform/artefacts/form.md
      - html: platform/artefacts/html.md
      - job: platform/artefacts/job.md
      - js: platform/artefacts/js.md
      - listener: platform/artefacts/listener.md
      - markdown: platform/artefacts/markdown.md
      - model: platform/artefacts/model.md
      - odata: platform/artefacts/odata.md
      - openapi: platform/artefacts/openapi.md
      - py: platform/artefacts/python.md
      - role: platform/artefacts/role.md
      - schema: platform/artefacts/schema.md
      - table: platform/artefacts/table.md
      - template: platform/artefacts/template.md
      - ts: platform/artefacts/ts.md
      - view: platform/artefacts/view.md
      - websocket: platform/artefacts/websocket.md
      - additions:
        - 'platform/artefacts/additions/index.md'
        - abap: platform/artefacts/additions/abap.md
    - SDK:
      - 'platform/sdk/index.md'
      - BPM:
        - 'platform/sdk/bpm/index.md'
        - Process: 'platform/sdk/bpm/process.md'
      - CMS:
        - 'platform/sdk/cms/index.md'
        - CMIS: 'platform/sdk/cms/cmis.md'
      - Core:
        - 'platform/sdk/core/index.md'
        - Configurations: 'platform/sdk/core/configurations.md'
        - Context: 'platform/sdk/core/context.md'
        - Env: 'platform/sdk/core/env.md'
        - Globals: 'platform/sdk/core/globals.md'
      - Database:
        - 'platform/sdk/db/index.md'
        - DAO: 'platform/sdk/db/dao.md'
        - Database: 'platform/sdk/db/database.md'
        - Insert: 'platform/sdk/db/insert.md'
        - Procedure: 'platform/sdk/db/procedure.md'
        - Query: 'platform/sdk/db/query.md'
        - Sequence: 'platform/sdk/db/sequence.md'
        - Store: 'platform/sdk/db/store.md'
        - Update: 'platform/sdk/db/update.md'
      - Extensions:
        - 'platform/sdk/extensions/index.md'
      - Git:
        - 'platform/sdk/git/index.md'
        - Client: 'platform/sdk/git/client.md'
      - HTTP:
        - 'platform/sdk/http/index.md'
        - Async Client: 'platform/sdk/http/client-async.md'
        - Client: 'platform/sdk/http/client.md'
        - Request: 'platform/sdk/http/request.md'
        - Response: 'platform/sdk/http/response.md'
        - RESTful Framework: 'platform/sdk/http/rs.md'
        - Session: 'platform/sdk/http/session.md'
        - Upload: 'platform/sdk/http/upload.md'
      - Indexing:
        - 'platform/sdk/indexing/index.md'
        - Writer: 'platform/sdk/indexing/writer.md'
        - Searcher: 'platform/sdk/indexing/searcher.md'
      - IO:
        - 'platform/sdk/io/index.md'
        - Bites: 'platform/sdk/io/bytes.md'
        - Files: 'platform/sdk/io/files.md'
        - FTP: 'platform/sdk/io/ftp.md'
        - Streams: 'platform/sdk/io/streams.md'
        - ZIP: 'platform/sdk/io/zip.md'
      - Job:
        - 'platform/sdk/job/index.md'
        - Scheduler: 'platform/sdk/job/scheduler.md'
      - Log:
        - 'platform/sdk/log/index.md'
        - Logging: 'platform/sdk/log/logging.md'
      - Mail:
        - 'platform/sdk/mail/index.md'
        - Client: 'platform/sdk/mail/client.md'
      - Messaging:
        - 'platform/sdk/messaging/index.md'
        - Consumer: 'platform/sdk/messaging/consumer.md'
        - Producer: 'platform/sdk/messaging/producer.md'
      - Net:
        - 'platform/sdk/net/index.md'
        - SOAP: 'platform/sdk/net/soap.md'
        - WebSocket: 'platform/sdk/net/websocket.md'
      - Platform:
        - 'platform/sdk/platform/index.md'
        - Command: 'platform/sdk/platform/command.md'
        - Lifecycle: 'platform/sdk/platform/lifecycle.md'
        - Registry: 'platform/sdk/platform/registry.md'
        - Repository: 'platform/sdk/platform/repository.md'
        - Workspace: 'platform/sdk/platform/workspace.md'
      - Security:
        - 'platform/sdk/security/index.md'
        - User: 'platform/sdk/security/user.md'
      - Template:
        - 'platform/sdk/template/index.md'
        - Engines: 'platform/sdk/template/engines.md'
      - Test:
        - 'platform/sdk/test/index.md'
        - Assert: 'platform/sdk/test/assert.md'
        - QUnit: 'platform/sdk/test/qunit.md'
        - Runner: 'platform/sdk/test/runner.md'
      - Utils:
        - 'platform/sdk/utils/index.md'
        - Alphanumeric: 'platform/sdk/utils/alphanumeric.md'
        - Base64: 'platform/sdk/utils/base64.md'
        - Digest: 'platform/sdk/utils/digest.md'
        - Escape: 'platform/sdk/utils/escape.md'
        - Hex: 'platform/sdk/utils/hex.md'
        - JSONPath: 'platform/sdk/utils/jsonpath.md'
        - QRCode: 'platform/sdk/utils/qrcode.md'
        - Url: 'platform/sdk/utils/url.md'
        - UTF8: 'platform/sdk/utils/utf8.md'
        - UUID: 'platform/sdk/utils/uuid.md'
        - XML: 'platform/sdk/utils/xml.md'
    - Widgets: 'platform/widgets/index.md'
    - Services: 'platform/services/index.md'
    # - Templates: 'platform/templates/index.md'
  - Tooling:
    - 'tooling/index.md'
    - Workbench:
      - 'tooling/workbench/index.md'
      - Projects: 'tooling/workbench/projects.md'
      - Import: 'tooling/workbench/import.md'
      - Search: 'tooling/workbench/search.md'
      - Properties: 'tooling/workbench/properties.md'
      - Console: 'tooling/workbench/console.md'
      - Preview: 'tooling/workbench/preview.md'
      - Problems: 'tooling/workbench/problems.md'
      - Logs: 'tooling/workbench/logs.md'
      - Loggers: 'tooling/workbench/loggers.md'
      - Code Editor: 'tooling/workbench/code-editor.md'
    - Git:
      - 'tooling/git/index.md'
      - Git Projects: 'tooling/git/git-projects.md'
      - Local Branches: 'tooling/git/local-branches.md'
      - Remote Branches: 'tooling/git/remote-branches.md'
      - Staging: 'tooling/git/staging.md'
      - History: 'tooling/git/history.md'
      - Diff Editor: 'tooling/git/diff-editor.md'
    - Debugger: 'tooling/debugger/index.md'
    - Databases:
      - 'tooling/databases/index.md'
      - Explorer: 'tooling/databases/explorer.md'
      - SQL: 'tooling/databases/sql.md'
      - NoSQL: 'tooling/databases/nosql.md'
      - Result: 'tooling/databases/result.md'
      - Databases: 'tooling/databases/databases.md'
      - Transfer: 'tooling/databases/transfer.md'
      - Export & Import: 'tooling/databases/export-import.md'
      - Anonymization: 'tooling/databases/data-anonymization.md'
    - Documents:
      - 'tooling/documents/index.md'
      - Explorer: 'tooling/documents/explorer.md'
      - Preview: 'tooling/documents/preview.md'
    - Processes:
      - 'tooling/processes/index.md'
      - Definitions: 'tooling/processes/definitions.md'
      - Instances: 'tooling/processes/instances.md'
      - Context: 'tooling/processes/context.md'
      - Dead-Letter Jobs: 'tooling/processes/dead-letter-jobs.md'
      - Viewer: 'tooling/processes/viewer.md'
      - Inbox: 'tooling/processes/inbox.md'
      - Modeler: 'tooling/processes/modeler.md'
    - Integrations: 'tooling/integrations/index.md'
    - Operations: 'tooling/operations/index.md'
    - Terminal: 'tooling/terminal/index.md'
    - Modeling:
      - 'tooling/modeling/index.md'
      - EDM: 'tooling/modeling/edm.md'
      - Form: 'tooling/modeling/form.md'
    - Extensibility: 'tooling/extensibility.md'
    - Compatibility: 'tooling/compatibility.md'
    - Multitenancy: 'tooling/multitenancy.md'
  - Modules:
    - 'modules/index.md'
    - Sales:
      - 'modules/sales/index.md'
      - Lead: 'modules/sales/lead.md'
      - Opportunity: 'modules/sales/opportunity.md'
      - Quotation: 'modules/sales/quotation.md'
      - Sales Order: 'modules/sales/sales-order.md'
      - Sales Invoice: 'modules/sales/sales-invoice.md'
      - Customer Payment: 'modules/sales/customer-payment.md'
    - Purchasing:
      - 'modules/purchasing/index.md'
      - Purchase Requisition: 'modules/purchasing/purchase-requisition.md'
      - Purchase Order: 'modules/purchasing/purchase-order.md'
      - Request for Quotation: 'modules/purchasing/request-for-quotation.md'
      - Quotation Comparison: 'modules/purchasing/quotation-comparison.md'
      - Supplier Aggreement: 'modules/purchasing/supplier-agreement.md'
      - Debit Note: 'modules/purchasing/debit-note.md'
      - Purchase Invoice: 'modules/purchasing/purchase-invoice.md'
      - Supplier Payment: 'modules/purchasing/supplier-payment.md'
    - Inventory:
      - 'modules/inventory/index.md'
      - Goods Receipt: 'modules/inventory/goods-receipt.md'
      - Goods Issue: 'modules/inventory/goods-issue.md'
      - Stock Transfer: 'modules/inventory/stock-transfer.md'
      - Stock Return: 'modules/inventory/stock-return.md'
      - Stock Record: 'modules/inventory/stock-record.md'
      - Stock Adjustment: 'modules/inventory/stock-adjustment.md'
      - SKU Listing: 'modules/inventory/sku-listing.md'
      - Store: 'modules/inventory/store.md'
    # - Stores: 'modules/stores.md'
    # - e-Commerce: 'modules/e-commerce.md'
    # - Projects: 'modules/projects.md'
    # - Timesheets: 'modules/timesheets.md'
    # - Employees: 'modules/employees.md'
    # - Salaries: 'modules/salaries.md'
    # - Payroll: 'modules/payroll.md'
    # - Vacations: 'modules/vacations.md'
    # - Billing: 'modules/billing.md'
    # - Payments: 'modules/payments.md'
    # - Shipping: 'modules/shipping.md'
    # - Services: 'modules/services.md'
    # - Manufactoring: 'modules/manufactoring.md'
    # - Hotels: 'modules/hotels.md'
    # - Restaurants: 'modules/restaurants.md'
    # - Accounting: 'modules/accounting.md'
    # - Master Data: 'modules/master-data.md'
    - Reference Data:
      - 'modules/reference-data/index.md'
      - Units of Measures: 'modules/reference-data/uom.md'




theme:
  name: material
  favicon: logo/favicon.png
  logo: logo/logo.svg
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/custom.css
  - stylesheets/homepage.css
  - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

copyright: Copyright Â© 2024 codbex ltd

extra:
  homepage: https://www.codbex.com/
  analytics:
    provider: google
    property: G-QWPZ5B9RH8
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codbex/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codbex/
    - icon: fontawesome/brands/github
      link: https://github.com/codbex/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCbxnGOhmcDvBIrafDeyCU7Q/videos/
